apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
  namespace: whoami
subjects:
- kind: ServiceAccount
  name: webserver-service-account
  namespace: whoami
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io