apiVersion: v1
data:
  nginx.conf: "worker_processes  auto;\n\nerror_log  /var/log/nginx/error.log notice;\npid
    \       /tmp/nginx.pid;\n\n\nevents {\n    worker_connections  1024;\n}\n\n\nhttp
    {\n    proxy_temp_path /tmp/proxy_temp;\n    client_body_temp_path /tmp/client_temp;\n
    \   fastcgi_temp_path /tmp/fastcgi_temp;\n    uwsgi_temp_path /tmp/uwsgi_temp;\n
    \   scgi_temp_path /tmp/scgi_temp;\n\n    include       /etc/nginx/mime.types;\n
    \   default_type  application/octet-stream;\n\n    log_format  main  '$remote_addr
    - $remote_user [$time_local] \"$request\" '\n                      '$status $body_bytes_sent
    \"$http_referer\" '\n                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';\n\n
    \   access_log  /var/log/nginx/access.log  main;\n\n    sendfile        on;\n
    \   #tcp_nopush     on;\n\n    keepalive_timeout  65;\n\n    #gzip  on;\n \n    #
    Set the content root\n    root /usr/share/nginx/html;\n\n    include /etc/nginx/conf.d/*.conf;\n}"
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: whoami
